models/Loginarko.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "login".
 *
 * @property int $id
 * @property string $username
 * @property string $cpf
 * @property string $password
 * @property string $authKey
 * @property string $accessToken
 * @property int $usuario_id
 * @property string $login_status
 *
 * @property Usuario $usuario
 */
class Loginarko extends \yii\db\ActiveRecord
{

    public $status_ativo = "ATIVO";
    public $status_inativo = "INATIVO";
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'login';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['authKey', 'accessToken', 'login_status'], 'string'],
            [['cpf','username','password','login_status'], 'required'],
            [['usuario_id'], 'integer'],
            [['username', 'cpf', 'password'], 'string', 'max' => 45],
            [['usuario_id'], 'exist', 'skipOnError' => true, 'targetClass' => Usuario::className(), 'targetAttribute' => ['usuario_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Nome de Usuário',
            'cpf' => 'CPF',
            'password' => 'Senha',
            'authKey' => 'Auth Key',
            'accessToken' => 'Access Token',
            'usuario_id' => 'Usuário',
            'login_status' => 'Status do Login',
        ];
    }

    public static function getUsuarioPorCpf($cpf){
        $usuario = Loginarko::find()->where(['cpf'=>$cpf])->one();
        return $usuario;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsuario()
    {
        return $this->hasOne(Usuario::className(), ['id' => 'usuario_id']);
    }
}

controllers/LoginarkoController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Loginarko;
use app\models\LoginarkoSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Usuario;
use app\models\User;
use app\models\Loghistorico;
/**
 * LoginarkoController implements the CRUD actions for Loginarko model.
 */
class LoginarkoController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Loginarko models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new LoginarkoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Loginarko model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Loginarko model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Loginarko();
        if ($model->load(Yii::$app->request->post() ) ){

            $usuario = Usuario::find()->where(['cpf'=>$model->cpf])->one();

            $model->usuario_id = Usuario::find()->where(['cpf'=>$model->cpf])->one()->id;
            
            $model->login_status = "ATIVO";

            if($model->save()){
                
                $log = Loghistorico::salvarLogHistorico(
                    intval(Yii::$app->user->identity->usuario_id),
                    'CADASTRAR LOGIN',
                    'LOGINARKO',
                    "Cadastrou login para o usuario: ({$model->usuario_id}) ".Usuario::findOne($model->usuario_id)->nome
                );
                $corpoEmail = 
                "
                    <h1>Confirmação de Acesso</h1>
                    <p>Usuario: {$model->cpf}</p>
                    <p>Senha: {$model->password}</p>
                    <p>Você pode acessar o sistemas com as informações acima.</p><br>
                ";
                Usuario::emailUsuario(
                    "layoutpadrao",
                    "Permissão de acesso",
                    $corpoEmail,
                    "sistemainventario@arkosolucoes.com.br",
                    $usuario->email,
                    "Arko Solutions- Permissão de acesso");

                if($log == false){
                    echo "erro no salvar log";die;
                }
                return $this->redirect(['view', 'id' => $model->id]);
            }
            die;
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Loginarko model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionAlterarsenha()
    {
        $model = new Loginarko();

        if (Yii::$app->request->post()){
            // echo "<pre>";print_r(Yii::$app->request->post());die;
            $model = $this->findModelByCpf(Yii::$app->request->post()['Loginarko']['cpf']);
            $usuario = Usuario::findOne($model->usuario_id);
            if($usuario->cargo != User::INVENTARIANTE){
                return json_encode(['STATUS'=>400,'message'=>'Este usuário não é inventariante!']);
            }
            $model->load(Yii::$app->request->post());
            if($model->save()){
                $log = Loghistorico::salvarLogHistorico(
                    intval(Yii::$app->user->identity->usuario_id),
                    'ALTERAR SENHA INVENTARIANTE',
                    'LOGINARKO',
                    "alterou senha para o usuario: ({$model->usuario_id}) ".Usuario::findOne($model->usuario_id)->nome
                );
                $corpoEmail = 
                "
                    <h1>Confirmação de Acesso</h1>
                    <p>Usuario: {$model->cpf}</p>
                    <p>Senha: {$model->password}</p>
                    <p>Você pode acessar o sistemas com as informações acima.</p><br>
                ";
                Usuario::emailUsuario(
                    "layoutpadrao",
                    "Permissão de acesso",
                    $corpoEmail,
                    "sistemainventario@arkosolucoes.com.br",
                    $usuario->email,
                    "Arko Solutions- Permissão de acesso");

                if($log == false){
                    echo "erro no salvar log";die;
                }
                return json_encode(['message'=>'Salvo com sucesso!']);
            }
        }

        return $this->render('nova-senha-inventariante', [
            'model' => $model,
        ]);
    }

    public function actionAlterarstatus($id){
        $model = $this->findModel($id);
        if(Yii::$app->request->get()){

            if($model->login_status == $model->status_ativo){
                $model->login_status = $model->status_inativo;
                if($model->save()){
                    $log = Loghistorico::salvarLogHistorico(
                        intval(Yii::$app->user->identity->usuario_id),
                        'ALTERAR STATUS LOGIN',
                        'LOGINARKO',
                        "desativou login Do usuario: ({$model->usuario_id}) ".Usuario::findOne($model->usuario_id)->nome
                    );
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }
            if($model->login_status == $model->status_inativo){
                $model->login_status = $model->status_ativo;
                $log = Loghistorico::salvarLogHistorico(
                    intval(Yii::$app->user->identity->usuario_id),
                    'ALTERAR STATUS LOGIN',
                    'LOGINARKO',
                    "ativou login Do usuario: ({$model->usuario_id}) ".Usuario::findOne($model->usuario_id)->nome
                );
                if($model->save()){
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }
            
        }

        

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionConsultalogin($cpf){
        if(Yii::$app->request->get()){
            $usuario = Loginarko::getUsuarioPorCpf(Yii::$app->request->get()['cpf']);
            return json_encode($usuario->attributes);
        }
    }

    public function actionConsultausuario($cpf){
        if(Yii::$app->request->get()){
            $usuario = Usuario::getUsuarioPorCpf(Yii::$app->request->get()['cpf']);
            return json_encode($usuario->attributes);
        }
    }

    /**
     * Updates an existing Loginarko model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $log = Loghistorico::salvarLogHistorico(
                intval(Yii::$app->user->identity->usuario_id),
                'ALTERAR LOGIN',
                'LOGINARKO',
                "alterou login Do usuario: ({$model->usuario_id}) ".Usuario::findOne($model->usuario_id)->nome
            );
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Loginarko model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    // public function actionDelete($id)
    // {
    //     $this->findModel($id)->delete();
    //     $log = Loghistorico::salvarLogHistorico(
    //         intval(Yii::$app->user->identity->usuario_id),
    //         'deletar LOGIN',
    //         'LOGINARKO',
    //         "deletou login : ({$id}) "
    //     );

    //     return $this->redirect(['index']);
    // }

    /**
     * Finds the Loginarko model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Loginarko the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Loginarko::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    protected function findModelByCpf($cpf)
    {
        if (($model = Loginarko::find()->where(['cpf'=>$cpf])->one()) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/loginarko/_form-alterar.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\models\Usuario;

/* @var $this yii\web\View */
/* @var $model app\models\Loginarko */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="loginarko-form">

<fieldset>
    <legend><h3>Alterar Acesso</h3></legend>
    <?php $form = ActiveForm::begin(); ?>

    <div class="col-md-12">
            <div class="metade">
                <div class="form-group field-loginarko-cpf">
                    <label class="control-label" for="loginarko-cpf">Cpf</label>
                    <input type="text" id="loginarko-cpf" class="cpf form-control" name="Loginarko[cpf]" maxlength="45" aria-invalid="false"><br>
                    <div class="btn btn-primary" onclick="getUsuarioAjax()">Consultar CPF</div>
                </div>                          
            </div>
            <div class="metade">
                <?= $form->field($model, 'login_status')->dropDownList([ 'ATIVO' => 'ATIVO', 'INATIVO' => 'INATIVO', ], ['prompt' => '']) ?>
            </div>   
        <div class="col-md-6">
            <div class="row">
                <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="row">
                <?= $form->field($model, 'usuario_id')->dropDownList(ArrayHelper::map(Usuario::find()->all(), 'id', 'nome'), ['prompt' => '', 'disabled'=>true]) ?>
            </div>
            
        </div>
        <div class="col-md-6">
            <div class="row">
                <?= $form->field($model, 'password')->passwordInput(['maxlength' => true,'placeholder'=>'Min. 4 dígitos']) ?>
            </div>
            <div class="row">
                <?= $form->field($model, 'password')->passwordInput(['maxlength' => true, 'name'=>'', 'id'=>'login-password-validation','placeholder'=>'****']) ?>
            </div>
        </div>
    </div>
</fieldset>

    <div class="form-group">
        <?= Html::submitButton('Salvar', ['class' => 'btn btn-success']) ?>
        <?= Html::a('Voltar', ['index'], ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<script src="../js/js-arko/jquery-3.3.1.min.js" ></script>
<script src="../js/js-arko/jquery.maskedinput.min.js" ></script>
<script>



function getUsuarioAjax(usu_cpf){
    let urlbase = window.location.origin;
    var request = $.ajax({
    url: urlbase+"/loginarko/consultausuario",
    type: "GET",
    data: {cpf : $("#loginarko-cpf").val()},
    dataType: ""
    });

    request.done(function(msg) {
        msg = JSON.parse(msg);
        let username = msg.nome;
        username = username.split(' ')[0];
        if($("#loginarko-username").val() == ""){
            $("#loginarko-username").val(username);
        }
        $("#loginarko-usuario_id").val(msg.id);
    });

    request.fail(function(jqXHR, textStatus) {
    alert( "Request failed: " + textStatus );
    });
}
    
$(document).ready(function($){
    $('.cpf').mask("999.999.999-99");    
})
</script>

views/loginarko/_form-novo.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\models\Usuario;

/* @var $this yii\web\View */
/* @var $model app\models\Loginarko */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="loginarko-form">

<fieldset>
    <legend><h3>Liberar Acesso</h3></legend>
    <?php $form = ActiveForm::begin(); ?>
    <div class="col-md-12">
        
            <div class="row">
                <div class="form-group field-loginarko-cpf">
                    <label class="control-label" for="loginarko-cpf">Cpf</label>
                    <input type="text" id="loginarko-cpf" class="cpf form-control" name="Loginarko[cpf]" maxlength="45" aria-invalid="false"><br>
                    <div class="btn btn-primary" onclick="getUsuarioAjax()">Consultar CPF</div>
                </div>                          
            </div>
            
        <div class="col-md-6">
            <div class="row">
                <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="row">
                <?= $form->field($model, 'usuario_id')->dropDownList(ArrayHelper::map(Usuario::find()->all(), 'id', 'nome'), ['prompt' => '', 'disabled'=>true]) ?>
            </div>
            
        </div>
        <div class="col-md-6">
            <div class="row">
                <?= $form->field($model, 'password')->passwordInput(['maxlength' => true,'placeholder'=>'Min. 4 dígitos']) ?>
            </div>
            <div class="row">
                <?= $form->field($model, 'password')->passwordInput(['maxlength' => true, 'name'=>'', 'id'=>'login-password-validation','placeholder'=>'****']) ?>
            </div>
        </div>
    </div>
</fieldset>

    <?php ActiveForm::end(); ?>

    <div class="form-group">
        <div class="btn btn-success" onclick="salvar()">Salvar</div>
        <?= Html::a('Voltar', ['index'], ['class' => 'btn btn-primary']) ?>
    </div>

    

</div>

<script src="../js/js-arko/jquery-3.3.1.min.js" ></script>
<script src="../js/js-arko/jquery.maskedinput.min.js" ></script>
<script>

function salvar(){
    if(validaPassword() == false){
        if(validaCPF() == true){
            if(validaUsuario() == true){
                $("#w0").submit();
            }
        }
    }
}

function validaCPF(){
    let preenchido = true;
    if($('.cpf').val()==""){
        $('.field-loginarko-cpf').addClass('has-error');
        preenchido = false;
    }else{
        $('.field-loginarko-cpf').removeClass('has-error');
    }
    return preenchido;
}

function validaUsuario(){
    let preenchido = false;
    if($("#loginarko-usuario_id").val()==""){
        sweetAlert('info', 'Consultar CPF' ,'consulte o cpf para preencher os demais campos')
    }else{
        preenchido = true;
    }
    return preenchido;
}

function getUsuarioAjax(usu_cpf){
    loading();
    var request = $.ajax({
    url: "<?php echo Url::to(['loginarko/consultausuario'])?>",
    type: "GET",
    data: {cpf : $("#loginarko-cpf").val()},
    dataType: ""
    });

    request.done(function(msg) {
        msg = JSON.parse(msg);
        let username = msg.nome;
        username = username.split(' ')[0];
        if($("#loginarko-username").val() == ""){
            $("#loginarko-username").val(username);
        }
        $("#loginarko-usuario_id").val(msg.id);
        encerraLoading();
    });

    request.fail(function(jqXHR, textStatus) {
        if(jqXHR.status){
            sweetAlert('info', 'CPF' ,'Informe um cpf valido');
        }
    });
}
    
$(document).ready(function($){
    $('#loginarko-login_status').val('ATIVO');
    $('.cpf').mask("999.999.999-99");    
})
</script>

views/loginarko/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Loginarko */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="loginarko-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'cpf')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'authKey')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'accessToken')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'usuario_id')->textInput() ?>

    <?= $form->field($model, 'login_status')->dropDownList([ 'ATIVO' => 'ATIVO', 'INATIVO' => 'INATIVO', ], ['prompt' => '']) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/loginarko/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\LoginarkoSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Acessos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="loginarko-index">

    <h3><?= Html::encode($this->title) ?></h3>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Liberar Acesso', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Recuperar Senha', ['alterarsenha'], ['class' => 'btn btn-primary']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'class' => 'yii\grid\SerialColumn',
                'contentOptions' => ['style' => 'width: 20px;', 'class' => 'text-center'],
            ],
            [
                'attribute' => 'username',
                'headerOptions' => ['class' => 'text-center'],
                'contentOptions' => ['style' => 'width: 40%; color:#337ab7;', 'class' => 'text-left'],
            ],
            [
                'attribute' => 'cpf',
                'headerOptions' => ['class' => 'text-center'],
                'contentOptions' => ['style' => 'width: 30%; color:#337ab7;', 'class' => 'text-left'],
            ],
            [
                'attribute' => 'login_status',
                'headerOptions' => ['class' => 'text-center'],
                'contentOptions' => ['style' => 'width: 10%; color:#337ab7;', 'class' => 'text-left'],
            ],

            [
            'class' => 'yii\grid\ActionColumn',
            'header'=>'Ações', 
            'headerOptions' => ['width' => '80','style'=>'width: 10%; color:#337ab7;', 'class'=>'text-center'],
            'template' => '{view} {update} {mudastatus} {impressaoficha} {produtividade}',
            'buttons' => [
                    'view' => function($url,$model,$key){
                        return Html::a('<span class="glyphicon glyphicon-eye-open" title="Visualizar"></span>', Url::to(['loginarko/view','id'=>$key]));
                    },
                    'update' => function($url,$model,$key){
                        return Html::a('<span class="glyphicon glyphicon-pencil" title="Alterar"></span>', Url::to(['loginarko/update','id'=>$key]));
                    },
                    'mudastatus' => function($url,$model,$key){
                        return Html::a('<span class="glyphicon glyphicon-off" title="Ativar/Desativar"></span>', Url::to(['loginarko/alterarstatus','id'=>$key]));
                    },
                ],
            ],
        ],
        // 'columns' => [
        //     ['class' => 'yii\grid\SerialColumn'],

        //     'id',
        //     'username',
        //     'cpf',
        //     // 'password',
        //     // 'authKey:ntext',
        //     //'accessToken:ntext',
        //     //'usuario_id',
        //     'login_status',
        //     ['class' => 'yii\grid\ActionColumn'],
        // ],
    ]); ?>
</div>

views/loginarko/nova-senha-inventariante.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use app\models\Usuario;


/* @var $this yii\web\View */
/* @var $model app\models\Loginarko */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="loginarko-form">

<fieldset>
    <legend><h3>Recuperar Acesso</h3></legend>
    <?php $form = ActiveForm::begin(['action' => 'alterarsenha']); ?>
    
    <div class="col-md-12">
            <div class="metade">
                <div class="form-group field-loginarko-cpf">
                    <label class="control-label" for="loginarko-cpf">Cpf</label>
                    <input type="text" id="loginarko-cpf" class="cpf form-control" name="Loginarko[cpf]" maxlength="45" aria-invalid="false"><br>
                    <div class="btn btn-primary" onclick="getUsuarioAjax()">Consultar CPF</div>
                </div>                          
            </div>
            <div class="metade">
                <?= $form->field($model, 'login_status')->dropDownList([ 'ATIVO' => 'ATIVO', 'INATIVO' => 'INATIVO', ], ['prompt' => '']) ?>
            </div>   
        <div class="col-md-6">
            <div class="row">
                <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="row">
                <?= $form->field($model, 'usuario_id')->dropDownList(ArrayHelper::map(Usuario::find()->all(), 'id', 'nome'), ['prompt' => '', 'disabled'=>true]) ?>
            </div>
            <!-- <div class="row">
                <div class="form-group field-loginarko-cpf">
                    <label class="control-label" for="loginarko-cpf">Cpf</label>
                    <input type="text" id="loginarko-cpf" class="cpf form-control" name="Loginarko[cpf]" maxlength="45" aria-invalid="false">
                    <div class="btn btn-primary" onclick="getUsuarioAjax()">Consultar cpf</div>
                </div>                          
            </div> -->
        </div>
        <div class="col-md-6">
            <div class="row">
                <?php //echo  $form->field($model, 'login_status')->dropDownList([ 'ATIVO' => 'ATIVO', 'INATIVO' => 'INATIVO', ], ['prompt' => '']) ?>
            </div>
            <div class="row">
                <?= $form->field($model, 'password')->passwordInput(['maxlength' => true,'placeholder'=>'Min. 4 dígitos']) ?>
            </div>
            <div class="row">
                <?= $form->field($model, 'password')->passwordInput(['maxlength' => true, 'name'=>'', 'id'=>'login-password-validation','placeholder'=>'****']) ?>
            </div>
        </div>
    </div>
</fieldset>
</fieldset>

    <?php ActiveForm::end(); ?>

    <div class="form-group">
        <div class="btn btn-success" onclick="gerarSenha()">Gerar Senha</div>
        <?php //echo Html::submitButton('Salvar', ['class' => 'btn btn-success']) ?>
    </div>

    

</div>

<script src="../js/js-arko/jquery-3.3.1.min.js" ></script>
<script src="../js/js-arko/jquery.maskedinput.min.js" ></script>
<script>

function salvar(){
    if(validaPassword() == false){
        if(validaCPF() == true){
            if(validaUsuario() == true){
                $("#w0").submit();
            }
        }
    }
}

function validaCPF(){
    let preenchido = true;
    if($('.cpf').val()==""){
        $('.field-loginarko-cpf').addClass('has-error');
        preenchido = false;
    }else{
        $('.field-loginarko-cpf').removeClass('has-error');
    }
    return preenchido;
}

function validaUsuario(){
    let preenchido = false;
    if($("#loginarko-usuario_id").val()==""){
        sweetAlert('info', 'Consultar CPF' ,'consulte o cpf para preencher os demais campos')
    }else{
        preenchido = true;
    }
    return preenchido;
}

function getUsuarioAjax(usu_cpf){
    loading();
    var request = $.ajax({
    url: "<?php echo Url::to(['loginarko/consultalogin'])?>",
    type: "GET",
    data: {cpf : $("#loginarko-cpf").val()},
    dataType: ""
    });

    request.done(function(msg) {
        msg = JSON.parse(msg);
        
        $("#loginarko-username").val(msg.username);
        $("#loginarko-usuario_id").val(msg.usuario_id);
        $("#loginarko-login_status").val(msg.login_status);
        encerraLoading();
    });

    request.fail(function(jqXHR, textStatus) {
        if(jqXHR.status){
            sweetAlert('info', 'CPF' ,'Informe um cpf valido');
        }
    });
}

function gerarSenha(){
    let senha = "";
    for(var i = 0; i< 4; i++){
        senha = senha+Math.floor((Math.random() * 9) + 1);
    }
    $('#loginarko-password').val(senha);
    $('#login-password-validation').val(senha);
    // sweetAlert('info','Nova senha: '+senha,'Clique em ok para salvar o login com a nova senha');
    swal({
        title: 'Nova senha: '+senha,
        type: 'info',
        html: 'Clique em ok para salvar o login com a nova senha',
        showCloseButton: false,
        showCancelButton: false,
        focusConfirm: true,
        // cancelButtonAriaLabel: 'Voltar',
        confirmButtonText:
            '<i class="fa fa-thumbs-up"></i> Salvar!',
        confirmButtonAriaLabel: 'Thumbs up, great!',
        preConfirm: function () {
            salvarRegistro();
        }
    });
}

function salvarRegistro(){
    
    let form = $("#w0");
    let url = form.attr('action');
    var request = $.ajax({
    url: url,
    type: "POST",
    data: form.serialize(),
    dataType: ""
    });

    request.done(function(msg) {
        msg = JSON.parse(msg);
        let tipo = 'success';
        let texto = "";
        let url = "<?php echo Url::to(['loginarko/index'])?>";
        if(msg.STATUS == 400){
            tipo = 'warning';
            texto = 'Verifique se o cpf está correto!';
            url = "#";
        }
        swal({
            title: msg.message,
            type: tipo,
            html: texto,
            showCloseButton: false,
            showCancelButton: false,
            focusConfirm: true,
            // cancelButtonAriaLabel: 'Voltar',
            confirmButtonText:
                '<i class="fa fa-thumbs-up"></i> ok!',
            confirmButtonAriaLabel: 'Thumbs up, great!',
            preConfirm: function () {
                window.location.href=url;
            }
        });
    });

    request.fail(function(jqXHR, textStatus) {
        if(jqXHR.status){
            sweetAlert('warning', 'erro' ,jqXHR.message);
        }
    });
}

$(document).ready(function($){
    $('.cpf').mask("999.999.999-99");    
})
</script>