models/Loja.php
<?php

namespace app\models;

use Yii;
use app\models\Agendamento;
use yiibr\brvalidator\CnpjValidator;


/**
 * This is the model class for table "loja".
 *
 * @property int $id
 * @property string $razao_social
 * @property string $nome_fantasia
 * @property string $cnpj
 * @property string $inscricao_municipal
 * @property string $endereco
 * @property string $endereco_numero
 * @property string $complemento
 * @property int $bairro_id
 * @property int $estado_id
 * @property int $cidade_id
 * @property string $cep
 * @property string $telefone
 * @property int $grupo_id
 * @property string $status
 * @property int $responsavel_id
 * @property string $latitude
 * @property string $longitude
 *
 * @property Contrato[] $contratos
 * @property Bairro $bairro
 * @property Cidade $cidade
 * @property Estado $estado
 * @property Grupo $grupo
 * @property Responsavel $responsavel
 */
class Loja extends \yii\db\ActiveRecord
{
    CONST STATUS_ATIVO = 'ATIVO';
    CONST STATUS_INATIVO = 'INATIVO';
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'loja';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['bairro_id', 'estado_id', 'cidade_id', 'grupo_id', 'responsavel_id','status','cnpj','inscricao_municipal'], 'required', 'message'=>'Campo não pode ser vazio'],
            [['bairro_id', 'estado_id', 'cidade_id', 'grupo_id', 'responsavel_id'], 'integer'],
            [['status'], 'string'],
            [['cnpj'],'unique','message'=>'Documento ja cadastrado'],
            ['cnpj', CnpjValidator::className(),'message'=>'Documento inválido'],
            [['razao_social'], 'string', 'max' => 200],
            [['nome_fantasia', 'inscricao_municipal'], 'string', 'max' => 100],
            [['cnpj', 'endereco_numero', 'complemento', 'cep', 'telefone', 'latitude', 'longitude'], 'string', 'max' => 45],
            [['endereco'], 'string', 'max' => 150],
            [['bairro_id'], 'exist', 'skipOnError' => true, 'targetClass' => Bairro::className(), 'targetAttribute' => ['bairro_id' => 'id']],
            [['cidade_id'], 'exist', 'skipOnError' => true, 'targetClass' => Cidade::className(), 'targetAttribute' => ['cidade_id' => 'id']],
            [['estado_id'], 'exist', 'skipOnError' => true, 'targetClass' => Estado::className(), 'targetAttribute' => ['estado_id' => 'id']],
            [['grupo_id'], 'exist', 'skipOnError' => true, 'targetClass' => Grupo::className(), 'targetAttribute' => ['grupo_id' => 'id']],
            [['responsavel_id'], 'exist', 'skipOnError' => true, 'targetClass' => Responsavel::className(), 'targetAttribute' => ['responsavel_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'razao_social' => 'Razao Social',
            'nome_fantasia' => 'Nome Fantasia',
            'cnpj' => 'Cnpj',
            'inscricao_municipal' => 'Inscricao Municipal',
            'endereco' => 'Endereco',
            'endereco_numero' => 'Endereco Numero',
            'complemento' => 'Complemento',
            'bairro_id' => 'Bairro',
            'estado_id' => 'Estado',
            'cidade_id' => 'Cidade',
            'cep' => 'Cep',
            'telefone' => 'Telefone',
            'grupo_id' => 'Grupo',
            'status' => 'Status',
            'responsavel_id' => 'Responsavel',
            'latitude' => 'Latitude',
            'longitude' => 'Longitude',
        ];
    }

    public static function getInventarios($id){
        $inventarios = [];
        $inventarios_aux = Inventario::find()->where(['LIKE','numero_inventario','L'.$id.'-'])->all();
        foreach( $inventarios_aux as $inventario){
            array_push($inventarios, ["id" => $inventario->id , "numero_inventario" => $inventario->numero_inventario]);
        }
        return $inventarios;
    }

    public static function getLojasComContratosConcluidos(){
        $resultado = [];
        $lojas = Loja::find()->where(['status'=>Loja::STATUS_ATIVO])->all();
        
        foreach ($lojas as $loja) {
            $tem_contrato_ativo = false;
            $contratos_concluidos = 
                Contrato::find()
                ->where(['loja_id'=>$loja->id])
                ->andWhere(['not in','contrato_status',[
                    Contrato::STATUS_ABERTO,
                    Contrato::STATUS_EM_ANDAMENTO,
                    // Contrato::STATUS_VENCIDO,
                    Contrato::STATUS_CANCELADO,
                ]])
                ->all();
            if($contratos_concluidos){
                foreach ($contratos_concluidos as $contrato) {
                    $agendamentos = 
                        Agendamento::find()
                        ->where(['contrato_id'=>$contrato->id])
                        ->andWhere(['agendamento_status'=>Agendamento::STATUS_CONCLUIDO])
                        ->all();
                }
            }
            echo "<pre>"; print_r($agendamentos); die;
        }
        
    }

    public static function getPositionLojas(){
        $lojas = [];
        $connection = Yii::$app->getDb();
        $sql = $connection->createCommand("
            select 
                nome_fantasia,latitude,longitude from loja
            where 
                latitude != ''
            and 
                longitude != ''
            ");
        $dados = $sql->queryAll();
        foreach($dados as $value){
            array_push($lojas,[$value['nome_fantasia'],$value['latitude'],$value['longitude']]);
            
        }
        
        return $lojas;

    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContratos()
    {
        return $this->hasMany(Contrato::className(), ['loja_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBairro()
    {
        return $this->hasOne(Bairro::className(), ['id' => 'bairro_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCidade()
    {
        return $this->hasOne(Cidade::className(), ['id' => 'cidade_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstado()
    {
        return $this->hasOne(Estado::className(), ['id' => 'estado_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGrupo()
    {
        return $this->hasOne(Grupo::className(), ['id' => 'grupo_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getResponsavel()
    {
        return $this->hasOne(Responsavel::className(), ['id' => 'responsavel_id']);
    }
}

controllers/LojaController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Loja;
use app\models\LojaSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Responsavel;
use app\models\Loghistorico;
use yii\web\UploadedFile;
use app\models\Contrato;
use app\models\Agendamento;
use yii\helpers\Json;


/**
 * LojaController implements the CRUD actions for Loja model.
 */
class LojaController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Loja models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new LojaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionGetinventarios($id){
        $inventarios = Loja::getInventarios($id);
        return Json::encode($inventarios);
    }

    public function actionGetlojas(){
        $lojas = Loja::find()->all();
        return Json::encode($lojas);
    }

    /**
     * Displays a single Loja model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $responsavel = Responsavel::findOne($model->responsavel_id);
        $contratos = Contrato::find()->where(['loja_id'=>$model->id])->all();
        $contrato = new Contrato();
        $contrato_aux = new Contrato();
        $mensagem = "";

        if(Yii::$app->request->post()){
            $contrato_aux->attributes = Yii::$app->request->post()['Contrato'];
            $contrato->attributes = Yii::$app->request->post()['Contrato'];
            $contrato->loja_id = $model->id;
            $contrato->contrato_status = Contrato::STATUS_ABERTO;
            // Contrato::verificaSobreposicaoDeContrato($contrato);
            // $contrato->data_adesao = Contrato::dateToDateBR($contrato->data_adesao);
            // $contrato->data_vencimento = Contrato::dateToDateBR($contrato->data_vencimento);
            $contrato->contrato_arquivo = UploadedFile::getInstance($contrato, 'contrato_arquivo'); 
            // echo "<pre>"; print_r($contrato->attributes);die;
            $contratos_sobrepostos = Contrato::verificaSobreposicaoDeContrato($contrato);

            $transaction = Yii::$app->db->beginTransaction();
            try {
                if(!$contratos_sobrepostos){
                    if(Contrato::verificaAdesaoVencimento($contrato)){
                        if($contrato = Contrato::salvarContrato($model,$contrato)){
                            $contrato->contrato_status = Contrato::STATUS_ABERTO;   
                            if($contrato->validate()){
                                if($contrato->save()){
                                    $log = Loghistorico::salvarLogHistorico(
                                        intval(Yii::$app->user->identity->usuario_id),
                                        'CADASTRAR Contrato',
                                        'Contrato',
                                        "CADASTROU contrato: ({$contrato->id}) {$contrato->contrato_numero}"
                                    );
    
                                    $datas_pre_agendamento = Contrato::dividirOtempoDeContratoPeloNumeroDeInventarios($contrato);
                                    if($datas_pre_agendamento){
                                        foreach($datas_pre_agendamento as $key => $value){
                                            $agendamento = new Agendamento();
                                            $agendamento = Agendamento::preAgendamentoAutomaticoDeInventario($contrato->id, $value);
                                            // echo "<pre>";print_r($agendamento->attributes);die;
                                            if($agendamento->save()){
                                                $log = Loghistorico::salvarLogHistorico(
                                                    intval(Yii::$app->user->identity->usuario_id),
                                                    'CADASTRO AGENDAMENTO',
                                                    'Agendamento',
                                                    "pre agendou automaticamento contrato : ({$contrato->id}) {$contrato->contrato_numero} | data: {$value}"
                                                );
                                            }else{
                                                $mensagem = "Erro ao salvar pre agendamento";
                                                $transaction->rollBack();
                                                return $this->render('view-com-responsavel', [
                                                    'model' => $model,
                                                    'responsavel'=>$responsavel,
                                                    'contratos' => $contratos,
                                                    'contrato'=>$contrato,
                                                    'mensagem' => $mensagem
                                                ]);
                                            }
                                        }
        
                                        $transaction->commit();
                                        return $this->redirect(['view', 'id' => $model->id]);
                                    }else{
                                        $mensagem = "A quantidade de inventários excedeu a quantidade de dias do contrato.";
                                        $transaction->rollBack();
                                    }
                                }else{
                                    $mensagem = "Erro ao salvar contrato";
                                    $transaction->rollBack();
                                }
                            }else{
                                $mensagem = "Revise os campos de contrato";
                                $transaction->rollBack();
                            }
                        }else{
                            $contrato = $contrato_aux;
                            $mensagem = "Erro ao salvar arquivo contrato";
                            $transaction->rollBack();
                        }                            
                    }else{
                        $mensagem = "Datas de adesão e vencimento inválidas";
                        $transaction->rollBack();
                    }
                }else{
                    $texto = "";
                    foreach($contratos_sobrepostos as $contrato_numero){
                        if($texto == ""){
                            $texto = $contrato_numero."; ";
                        }else{
                            $texto = $texto . $contrato_numero. "; ";
                        }
                    }
                    $mensagem = "Datas invalidas, contratos sobrepostos: <b>".$texto."</b>";
                    $transaction->rollBack();
                }
                
            } catch (\Throwable $th) {
                $mensagem = "Erro ao salvar contrato, verifique se adicionou o arquivo.";
                $transaction->rollBack();
            }
        }
        return $this->render('view-com-responsavel', [
            'model' => $model,
            'responsavel'=>$responsavel,
            'contratos' => $contratos,
            'contrato'=>$contrato,
            'mensagem' => $mensagem
        ]);
    }

    public function actionAlterarstatus($id){
        $model = $this->findModel($id);
        if(Yii::$app->request->get()){

            if($model->status == Loja::STATUS_ATIVO){
                $model->status = Loja::STATUS_INATIVO;
                if($model->save()){
                    $log = Loghistorico::salvarLogHistorico(
                        intval(Yii::$app->user->identity->usuario_id),
                        'ALTERAR STATUS LOJA',
                        'LOJA',
                        "desativou LOJA: ({$model->id}) {$model->razao_social} | nome fantasia: {$model->nome_fantasia}"
                    );
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }
            if($model->status == Loja::STATUS_INATIVO){
                $model->status = Loja::STATUS_ATIVO;
                if($model->save()){
                    $log = Loghistorico::salvarLogHistorico(
                        intval(Yii::$app->user->identity->usuario_id),
                        'ALTERAR STATUS loja',
                        'loja',
                        "ativou loja: ({$model->id}) {$model->razao_social} | nome fantasia: {$model->nome_fantasia}"
                    );
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }
            
        }

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Loja model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Loja();
        $responsavel = new Responsavel();
        $contrato = new Contrato();
        $contrato_aux = new Contrato();
        $mensagem = "";

        if(Yii::$app->request->post()){
            $model->load(Yii::$app->request->post());
            $responsavel->attributes = Yii::$app->request->post()['Responsavel'];

views/loja/_form-alterar.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\models\Estado;
use app\models\Cidade;
use app\models\Bairro;
use app\models\Sexo;
use app\models\Grupo;
use app\models\Responsavel;

/* @var $this yii\web\View */
/* @var $model app\models\Loja */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="loja-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <fieldset>
        <Legend><h1>Alterar Loja</h1></legend>
        <div class="col-md-12">
            <div class="col-md-6">
                <div class="row">
                    <?= $form->field($model, 'razao_social')->textInput(['maxlength' => true]) ?>
                </div>
                <div class="row">
                    <?= $form->field($model, 'endereco')->textInput(['maxlength' => true]) ?>
                </div>
                <div class="row">

                    <div class="metade">
                        <?= $form->field($model, 'bairro_id')
                            ->dropDownList(
                                ArrayHelper::map(Bairro::find()->orderBy(['descricao'=>SORT_ASC])->all(), 'id', 'descricao'),         // Flat array ('id'=>'label')
                                ['prompt'=>'Selecione ','name'=>'Loja[bairro_id]']    // options
                            ); ?>
                    </div>
                    <div class="metade">
                        <?php //echo $form->field($model, 'estado_id')->textInput() ?>
                        <?= $form->field($model, 'estado_id')
                            ->dropDownList(
                                ArrayHelper::map(Estado::find()->orderBy(['nome'=>SORT_ASC])->all(), 'id', 'nome'),         // Flat array ('id'=>'label')
                                ['prompt'=>'Selecione ','name'=>'Loja[estado_id]']    // options
                            ); ?>
                    </div>
                    
                </div>
                <div class="row">
                    <?php echo $form->field($model, 'telefone')->textInput(['maxlength' => true,'class'=>'form-control telefone']) ?>
                </div>
                <div class="row">
                    <?= $form->field($model, 'inscricao_municipal')->textInput(['maxlength' => true]) ?>
                </div>
            </div>

            <div class="col-md-6">

                <div class="row">

                    <div class="metade">
                        <?= $form->field($model, 'nome_fantasia')->textInput(['maxlength' => true]) ?>
                    </div>
                    <div class="metade">
                        <?php echo $form->field($model, 'cnpj')->textInput(['maxlength' => true,'class'=>"form-control cnpj",'disabled'=>true]) ?>
                    </div>

                </div>

                <div class="row">

                    <div class="metade">
                        <?= $form->field($model, 'endereco_numero')->textInput(['maxlength' => true]) ?>
                    </div>
                    <div class="metade">
                        <?php echo $form->field($model, 'cep')->textInput(['maxlength' => true,'class'=>'form-control cep']) ?>
                    </div>
                    <div class="metade">
                        <?php echo $form->field($model, 'latitude')->textInput(['maxlength' => true,'class'=>'form-control ']) ?>
                    </div>
                    
                    <div class="metade">
                        <?php echo $form->field($model, 'longitude')->textInput(['maxlength' => true,'class'=>'form-control ']) ?>
                    </div>

                </div>

                <div class="row">

                    <div class="metade">
                        <?php //echo $form->field($model, 'cidade_id')->textInput() ?>
                        <?= $form->field($model, 'cidade_id')
                            ->dropDownList(
                                ArrayHelper::map(Cidade::find()->orderBy(['nome'=>SORT_ASC])->all(), 'id', 'nome'),         // Flat array ('id'=>'label')
                                ['prompt'=>'Selecione ','name'=>'Loja[cidade_id]']    // options
                            ); ?>
                    </div>
                    <div class="metade">
                        <?= $form->field($model, 'complemento')->textInput(['maxlength' => true]) ?>
                    </div>

                </div>

                <div class="row">

                    <div class="metade">
                        <?php //echo $form->field($model, 'grupo_id')->textInput() ?>
                        <?= $form->field($model, 'grupo_id')
                            ->dropDownList(
                                ArrayHelper::map(Grupo::find()->where(['grupo_status'=>Grupo::STATUS_ATIVO])->orderBy(['grupo_nome'=>SORT_ASC])->all(), 'id', 'grupo_nome'),         // Flat array ('id'=>'label')
                                ['prompt'=>'Selecione ','name'=>'Loja[grupo_id]']    // options
                            ); ?>
                    </div>
                    <div class="metade">
                        <?= $form->field($model, 'status')->dropDownList([ 'ATIVO' => 'ATIVO', 'INATIVO' => 'INATIVO', ], ['prompt' => '']) ?>
                    </div>

                </div>

            </div>
        </div>
    </fieldset>

    <fieldset>
        <Legend>Responsável</legend>
        <div class="col-md-12">
            <div class="col-md-6">
                <div class="row">
                    <?= $form->field($responsavel, 'nome')->textInput(['maxlength' => true]) ?>
                </div>
                <div class="row">

                    <div class="metade">
                        <?php echo $form->field($responsavel, 'nascimento')->Input('date') ?>
                    </div>
                    <div class="metade">
                        <?php //echo $form->field($model, 'sexo_id')->textInput() ?>
                        <?= $form->field($responsavel, 'sexo')->dropDownList([ 'MASCULINO' => 'MASCULINO', 'FEMININO' => 'FEMININO', 'OUTROS' => 'OUTROS', ], ['prompt' => '']) ?>
                    </div>
                    
                </div>
                <div class="row">
                    <?= $form->field($responsavel, 'email')->input('email') ?>
                </div>
            </div>

            <div class="col-md-6">

                <div class="row">

                    <div class="metade">
                        <?= $form->field($responsavel, 'rg')->textInput(['maxlength' => true]) ?>
                    </div>
                    <div class="metade">
                        <?= $form->field($responsavel, 'cpf')->textInput(['maxlength' => true,'class'=>'form-control cpf','disabled'=>true]) ?>
                    </div>

                </div>

                <div class="row">

                    <div class="metade">
                        <?= $form->field($responsavel, 'cargo')->textInput(['maxlength' => true]) ?>
                    </div>
                    <div class="metade">
                        <?php echo $form->field($responsavel, 'telefone')->textInput(['maxlength' => true,'class'=>'form-control telefone']) ?>
                    </div>
                </div>

            </div>
        </div>
    </fieldset>

    <?php ActiveForm::end(); ?>

    <div class="row" >
        <div class="btn btn-info" style="margin: 0px 0px 0px 46%;" onclick="submit()">
            Salvar
        </div>
    </div>   

</div>


<script src="../js/js-arko/jquery-3.3.1.min.js" ></script>
<script src="../js/js-arko/jquery.maskedinput.min.js" ></script>
<script>

    function submit(){
        localizacao();
        // lat = document.getElementById("loja-latitude").value;
        // lng = document.getElementById("loja-longitude").value;
        // if((lat == "") || (lng == "") ){
        //     localizacao();
        // }else{
        //     $('#w0').submit();
        // }
    }

    function localizacao(){

        loading();
        let rua = document.getElementById("loja-endereco").value;
        let bairro = $("#loja-bairro_id option:selected").text();
        let num = document.getElementById("loja-endereco_numero").value;
        let cidade = $("#loja-cidade_id option:selected").text();
        let estado = $("#loja-estado_id option:selected").text();

        let myRequest = "https://maps.googleapis.com/maps/api/geocode/json?address="
        +num+","
        +rua+","
        +bairro+","
        +cidade+","
        +estado+
        "&key=AIzaSyDfrATuTFCBcf1sbKD-QY0x4UHSS_lB20A";

        fetch(myRequest)
        .then( function(resposta){ 
            resposta.json().then(function (json){
                document.getElementById('loja-latitude').value = json.results[0].geometry.location.lat;
                document.getElementById('loja-longitude').value = json.results[0].geometry.location.lng;
            }).then(function(){
                $('#w0').submit();
                // encerraLoading();
            })
        });
    }


    var mensagem = "<?php echo $mensagem; ?>"
    $(document).ready(function($){
        $('.cpf').mask("999.999.999-99");
        $('.cep').mask("99999-999");
        $('.telefone').mask("(99)99999-9999");
        $('.data  ').mask("99/99/9999");
        $('.cnpj').mask('99.999.999/9999-99', {reverse: false});
        if(mensagem != ""){
            sweetAlert('info','Erro',mensagem);
        }
        
    })
</script>

views/loja/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Loja */

$this->title = 'Cadastro de Loja';
$this->params['breadcrumbs'][] = ['label' => 'Lojas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="loja-create">

    <?= $this->render('_form-novo', [
        'model' => $model,
        'responsavel' => $responsavel,
        'contrato' => $contrato,
        'mensagem'=>$mensagem
    ]) ?>

</div>

views/loja/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use app\models\Responsavel;

/* @var $this yii\web\View */
/* @var $searchModel app\models\LojaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Lojas';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="loja-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Cadastrar Loja', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php 
        //  GridView::widget([
        //     'dataProvider' => $dataProvider,
        //     'filterModel' => $searchModel,
        //     'columns' => [
        //         ['class' => 'yii\grid\SerialColumn'],

        //         'id',
        //         'razao_social',
        //         'nome_fantasia',
        //         'cnpj',
        //         'inscricao_municipal',
        //         //'endereco',
        //         //'endereco_numero',
        //         //'complemento',
        //         //'bairro_id',
        //         //'estado_id',
        //         //'cidade_id',
        //         //'cep',
        //         //'telefone',
        //         //'grupo_id',
        //         //'status',
        //         //'responsavel_id',
        //         //'latitude',
        //         //'longitude',

        //         ['class' => 'yii\grid\ActionColumn'],
        //     ],
        // ]); 
    ?>
    <?= 
        GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                [
                    'class' => 'yii\grid\SerialColumn',
                    'contentOptions' => ['style' => 'width: 20px;', 'class' => 'text-center'],
                ],
                [
                    'attribute' => 'razao_social',
                    'headerOptions' => ['class' => 'text-center'],
                    'contentOptions' => ['style' => 'width: 20%; color:#337ab7;', 'class' => 'text-left'],
                ],
                [
                    'attribute' => 'nome_fantasia',
                    'headerOptions' => ['class' => 'text-center'],
                    'contentOptions' => ['style' => 'width: 20%; color:#337ab7;', 'class' => 'text-left'],
                ],
                [
                    'attribute' => 'cnpj',
                    'headerOptions' => ['class' => 'text-center'],
                    'contentOptions' => ['style' => 'width: 20%; color:#337ab7;', 'class' => 'text-left'],
                ],
                [
                    'attribute' => 'responsavel_id',
                    'headerOptions' => ['class' => 'text-center'],
                    'value'  => function ($data) {
                        return Responsavel::findOne($data->responsavel_id)->nome;
                    },
                    'contentOptions' => ['style' => 'width: 20%; color:#337ab7;', 'class' => 'text-left'],
                ],
                [
                    'attribute' => 'status',
                    'headerOptions' => ['class' => 'text-center'],
                    'contentOptions' => ['style' => 'width: 20%; color:#337ab7;', 'class' => 'text-left'],
                ],
    
                [
                'class' => 'yii\grid\ActionColumn',
                'header'=>'Ações', 
                'headerOptions' => ['width' => '80','style'=>'width: 10%; color:#337ab7;', 'class'=>'text-center'],
                'template' => '{view} {update} {mudastatus} {impressao}',
                'buttons' => [
                        'view' => function($url,$model,$key){
                            return Html::a('<span class="glyphicon glyphicon-eye-open" title="Visualizar"></span>', Url::to(['loja/view','id'=>$key]));
                        },
                        'update' => function($url,$model,$key){
                            return Html::a('<span class="glyphicon glyphicon-pencil" title="Alterar"></span>', Url::to(['loja/update','id'=>$key]));
                        },
                        'mudastatus' => function($url,$model,$key){
                            return Html::a('<span class="glyphicon glyphicon-off" title="Ativar/Desativar"></span>', Url::to(['loja/alterarstatus','id'=>$key]));
                        },
                        'impressao' => function($url,$model,$key){
                            return Html::a('<span class="glyphicon glyphicon-file" title="Imprimir"></span>', Url::to(['#']));
                        },
                    ],
                ],
            ],
        ]); 
    ?>
</div>